namespace DBZMOD.Enums
{
    // monolith of player vars that might need syncing, making it slightly easier to sync for specific objects.
    public enum PlayerVarSyncEnum
    {
        KiMax2,
        KiMax3,
        KiMaxMult,
        KiCurrent,
        isTransforming,
        Fragment1,
        Fragment2,
        Fragment3,
        Fragment4,
        Fragment5,
        IsCharging,
        JungleMessage,
        HellMessage,
        EvilMessage,
        MushroomMessage,
        IsHoldingKiWeapon,
        TraitChecked,
        PlayerTrait,
        IsFlying,
        IsTransformationAnimationPlaying,
        TriggerMouseLeft,
        TriggerMouseRight,        
        TriggerLeft,
        TriggerRight,
        TriggerUp,
        TriggerDown,
        ChargeMoveSpeed,
        BonusSpeedMultiplier,
        KaiokenLevel,
        MouseWorldOctant,
        PowerWishesLeft,
        HeldProjectile,
        WishActive,
        FacingDirection,
        IsMassiveBlastCharging,
        IsMassiveBlastInUse
    }
}
